### ISSUE TITLE
Not recognizing glob

### ISSUE THREAD

**Issue by VinnyOG** [grailbio/bazel-compilation-database#12]
When I do this:
`srcs = glob(["**/*"], exclude=["bazel-*"]) + ["@nasm//:nasm"],`
I get this:
`'//third-party/x264:configure' in $(location) expression is not a declared prerequisite of this rule`

When I do this:
` srcs = glob(["**/*"], exclude=["bazel-*"]) + ["@nasm//:nasm", "configure"],`
I get this:
` Label '@x264//:configure' is duplicated in the 'srcs' attribute of rule 'x264-build'`

So I'm forced to do this:
`srcs = glob(["**/*"], exclude=["bazel-*", "configure"]) + ["@nasm//:nasm", "configure"],`
Which gets me  this:
` //third-party/x264:x264-build: missing input file '//third-party/x264:configure'`

Now this is patently absurd! What gives?

Probably should add that bazel build everything correctly and runs without a problem, this issue is only present when running this library, either from the script or as a rule.

Happens in both case:
` $(location @nasm//:configure))`
` $(location configure))`

**Comment by siddharthab** [comment]
I don't quite understand your setup because your messages speak both of `@x264//:configure` and `//third-party/x264:configure`. It looks like your glob definitions are defining `@x264//:configure` but somewhere in your code you are expecting `//third-party/x264:configure`.

I don't think this is related to this project. It could be that aspects in bazel have stricter requirements than building. Makes sense because aspects came later, and so did not have backward compatibility requirements with old code.

**Comment by VinnyOG** [comment]
That's really the issue, it's expecting `//third-party/x264:configure` where as `$(location configure)` should be return `@x264//:configure` because that's where the file actually exists. Normal bazel builds run without a problem so I imagine this tool isn't properly setting up some path that `location` relies on.

**Comment by VinnyOG** [comment]
I'm sorry. I'm new to bazel.
I was building `bazel build //...`
But I changed it to build just this rule `bazel build compile_commands`
Those libraries were never meant to be stand alone builds like what I was erroneously doing with that command.

Sorry for the trouble and thanks for the awesome script!
