### ISSUE TITLE
generate.py doesn't filter out unsupported flag

### ISSUE THREAD

**Issue by asparagii** [grailbio/bazel-compilation-database#93]
As of version 13.0.1, `clang` doesn't support the flag `-fno-canonical-system-headers`.
The generated compile_commands.json might contain this flag, since the generation script doesn't filter it out.

We should filter out this flag.

**Comment by siddharthab** [comment]
If the compiler does not support the flag, then bazel should not be using the flag. And if bazel is not using the flag, then compile_commands.json would not have it. Is that not the case? Can you check the exact command line as used by bazel and compare with what is in compile_commands.json?

**Comment by asparagii** [comment]
We are using gcc to compile our codebase, so Bazel is using it - and of course the flag is supported in gcc.
Since this utility tries to generate a compile_commands even from Bazel configurations using gcc instead of clang, it would be useful if it filtered out unsupported options.

**Comment by asparagii** [comment]
Makes sense. I'm working on a project that can be compiled only with a specific version of gcc, I cannot change compiler at will (because of a dependency). Without the flag filtering, this generates an error message in each file when using clangd. Using my fork removing the flag there's no such error, of course.
If you don't want to take care of unsupported flags (reasonable choice) you can close this issue.
Thanks for your time.

**Comment by siddharthab** [comment]
Thanks for the response. Closing this issue because the recommended solution here would be to generate the compile_commands.json file with `CC=clang` in the environment, which will get bazel to output the right compile commands. And so even if the project does not compile with clang, at least the compile commands will have the right flags for libclang.

Alternatively, this could be set as the default env when calling bazel inside `generate.py`, but people might have different choices for what they want to use here.
